# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'borrow_book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import * 
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
import platform

if platform.system() == 'Windows':
   abs_path = (("\\").join((os.getcwd()).split("\\")[:-1])).replace('\\','\\\\')
if platform.system() == 'Linux':
   abs_path = ("/").join((os.getcwd()).split("/")[:-1])+"/"
sys.path.insert(0,r'{}'.format(abs_path))

from qrc_files import images_rc



class Ui_BorrowBook(object):
    def setupUi(self, BorrowBook):
        BorrowBook.setObjectName("BorrowBook")
        BorrowBook.resize(1920, 1080)
        BorrowBook.setMaximumSize(QtCore.QSize(1920, 1080))
        BorrowBook.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(BorrowBook)
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.frame.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame.setStyleSheet("background-image: url(:/bg_images/bg_main.png);\n"
"background-repeat: no-repeat; \n"
"background-position: center;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.borrow_book_label = QtWidgets.QLabel(self.frame)
        self.borrow_book_label.setGeometry(QtCore.QRect(560, 10, 741, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.borrow_book_label.setFont(font)
        self.borrow_book_label.setStyleSheet("QLabel{\n"
"color: rgb(105, 157, 238);\n"
"background: rgba( 4, 7, 15, 0 );\n"
"}\n"
"")
        self.borrow_book_label.setAlignment(QtCore.Qt.AlignCenter)
        self.borrow_book_label.setWordWrap(True)
        self.borrow_book_label.setObjectName("borrow_book_label")
        self.go_to_home = QtWidgets.QPushButton(self.frame)
        self.go_to_home.setGeometry(QtCore.QRect(50, 40, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.go_to_home.setFont(font)
        self.go_to_home.setStyleSheet("QPushButton{\n"
"     border-radius:30px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 15pt \"Segoe UI Semibold\";\n"
"    background: rgb(105, 157, 238);\n"
"\n"
"}\n"
"\n"
"QPushButton::hover:!pressed\n"
"{\n"
"background: rgb(105, 157, 238);\n"
"border : 2px solid black;\n"
"}")
        self.go_to_home.setObjectName("go_to_home")
        self.user_id_combobox = QtWidgets.QComboBox(self.frame)
        self.user_id_combobox.setGeometry(QtCore.QRect(270, 190, 281, 61))
        self.user_id_combobox.setStyleSheet("QComboBox{\n"
"    background: rgb(105, 157, 238);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(105, 157, 238);\n"
"}")
        self.user_id_combobox.setObjectName("user_id_combobox")
        self.confirm_button = QtWidgets.QPushButton(self.frame)
        self.confirm_button.setGeometry(QtCore.QRect(1190, 190, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.confirm_button.setFont(font)
        self.confirm_button.setStyleSheet("QPushButton{\n"
"     border-radius:30px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 15pt \"Segoe UI Semibold\";\n"
"    background: rgb(105, 157, 238);\n"
"\n"
"}\n"
"\n"
"QPushButton::hover:!pressed\n"
"{\n"
"background: rgb(105, 157, 238);\n"
"border : 2px solid black;\n"
"}")
        self.confirm_button.setObjectName("confirm_button")
        self.book_combobox = QtWidgets.QComboBox(self.frame)
        self.book_combobox.setGeometry(QtCore.QRect(630, 190, 501, 61))
        self.book_combobox.setStyleSheet("QComboBox{\n"
"    background: rgb(105, 157, 238);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(105, 157, 238);\n"
"}")
        self.book_combobox.setObjectName("book_combobox")
        self.status_label = QtWidgets.QLabel(self.frame)
        self.status_label.setGeometry(QtCore.QRect(260, 820, 1371, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"background: rgba( 4, 7, 15, 0 );\n"
"}")
        self.status_label.setText("")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        BorrowBook.setCentralWidget(self.centralwidget)

        self.retranslateUi(BorrowBook)
        QtCore.QMetaObject.connectSlotsByName(BorrowBook)

    def retranslateUi(self, BorrowBook):
        _translate = QtCore.QCoreApplication.translate
        self.borrow_book_label.setText(_translate("BorrowBook", "BORROW BOOK"))
        self.go_to_home.setText(_translate("BorrowBook", "HOME"))
        self.confirm_button.setText(_translate("BorrowBook", "CONFIRM"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BorrowBook = QtWidgets.QMainWindow()
    ui = Ui_BorrowBook()
    ui.setupUi(BorrowBook)
    BorrowBook.show()
    sys.exit(app.exec_())
