# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_stats.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import * 
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
import platform

if platform.system() == 'Windows':
   abs_path = (("\\").join((os.getcwd()).split("\\")[:-1])).replace('\\','\\\\')
if platform.system() == 'Linux':
   abs_path = ("/").join((os.getcwd()).split("/")[:-1])+"/"
sys.path.insert(0,r'{}'.format(abs_path))

from qrc_files import images_rc



class Ui_UserStats(object):
    def setupUi(self, UserStats):
        UserStats.setObjectName("UserStats")
        UserStats.resize(1920, 1080)
        UserStats.setMaximumSize(QtCore.QSize(1920, 1080))
        UserStats.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(UserStats)
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.frame.setMaximumSize(QtCore.QSize(1920, 1080))
        self.frame.setStyleSheet("background-image: url(:/bg_images/bg_main.png);\n"
"background-repeat: no-repeat; \n"
"background-position: center;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.user_stats_label = QtWidgets.QLabel(self.frame)
        self.user_stats_label.setGeometry(QtCore.QRect(560, 10, 741, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.user_stats_label.setFont(font)
        self.user_stats_label.setStyleSheet("QLabel{\n"
"color: rgb(105, 157, 238);\n"
"background: rgba( 4, 7, 15, 0 );\n"
"}\n"
"")
        self.user_stats_label.setAlignment(QtCore.Qt.AlignCenter)
        self.user_stats_label.setWordWrap(True)
        self.user_stats_label.setObjectName("user_stats_label")
        self.go_to_home = QtWidgets.QPushButton(self.frame)
        self.go_to_home.setGeometry(QtCore.QRect(50, 40, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.go_to_home.setFont(font)
        self.go_to_home.setStyleSheet("QPushButton{\n"
"     border-radius:30px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 15pt \"Segoe UI Semibold\";\n"
"    background: rgb(105, 157, 238);\n"
"\n"
"}\n"
"\n"
"QPushButton::hover:!pressed\n"
"{\n"
"background: rgb(105, 157, 238);\n"
"border : 2px solid black;\n"
"}")
        self.go_to_home.setObjectName("go_to_home")
        self.confirm_button = QtWidgets.QPushButton(self.frame)
        self.confirm_button.setGeometry(QtCore.QRect(990, 190, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.confirm_button.setFont(font)
        self.confirm_button.setStyleSheet("QPushButton{\n"
"     border-radius:30px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 63 15pt \"Segoe UI Semibold\";\n"
"    background: rgb(105, 157, 238);\n"
"\n"
"}\n"
"\n"
"QPushButton::hover:!pressed\n"
"{\n"
"background: rgb(105, 157, 238);\n"
"border : 2px solid black;\n"
"}")
        self.confirm_button.setObjectName("confirm_button")
        self.user_id_combobox = QtWidgets.QComboBox(self.frame)
        self.user_id_combobox.setGeometry(QtCore.QRect(640, 190, 281, 61))
        self.user_id_combobox.setStyleSheet("QComboBox{\n"
"    background: rgb(105, 157, 238);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(105, 157, 238);\n"
"}")
        self.user_id_combobox.setObjectName("user_id_combobox")
        self.no_of_books_read_label = QtWidgets.QLabel(self.frame)
        self.no_of_books_read_label.setGeometry(QtCore.QRect(190, 800, 451, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.no_of_books_read_label.setFont(font)
        self.no_of_books_read_label.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"background: rgb(105, 157, 238);\n"
"}")
        self.no_of_books_read_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_of_books_read_label.setObjectName("no_of_books_read_label")
        self.no_of_books_read_box = QtWidgets.QLabel(self.frame)
        self.no_of_books_read_box.setGeometry(QtCore.QRect(650, 800, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.no_of_books_read_box.setFont(font)
        self.no_of_books_read_box.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"background: rgb(105, 157, 238);\n"
"}")
        self.no_of_books_read_box.setText("")
        self.no_of_books_read_box.setAlignment(QtCore.Qt.AlignCenter)
        self.no_of_books_read_box.setObjectName("no_of_books_read_box")
        self.no_of_inhand_books_label = QtWidgets.QLabel(self.frame)
        self.no_of_inhand_books_label.setGeometry(QtCore.QRect(900, 800, 491, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.no_of_inhand_books_label.setFont(font)
        self.no_of_inhand_books_label.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"background: rgb(105, 157, 238);\n"
"}")
        self.no_of_inhand_books_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_of_inhand_books_label.setObjectName("no_of_inhand_books_label")
        self.no_of_inhand_books_box = QtWidgets.QLabel(self.frame)
        self.no_of_inhand_books_box.setGeometry(QtCore.QRect(1400, 800, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.no_of_inhand_books_box.setFont(font)
        self.no_of_inhand_books_box.setStyleSheet("QLabel{\n"
"color: rgb(255, 255, 255);\n"
"background: rgb(105, 157, 238);\n"
"}")
        self.no_of_inhand_books_box.setText("")
        self.no_of_inhand_books_box.setAlignment(QtCore.Qt.AlignCenter)
        self.no_of_inhand_books_box.setObjectName("no_of_inhand_books_box")
        UserStats.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserStats)
        QtCore.QMetaObject.connectSlotsByName(UserStats)

    def retranslateUi(self, UserStats):
        _translate = QtCore.QCoreApplication.translate
        self.user_stats_label.setText(_translate("UserStats", "USER STATS"))
        self.go_to_home.setText(_translate("UserStats", "HOME"))
        self.confirm_button.setText(_translate("UserStats", "CONFIRM"))
        self.no_of_books_read_label.setText(_translate("UserStats", "NO OF BOOKS READ :"))
        self.no_of_inhand_books_label.setText(_translate("UserStats", "NO OF INHAND BOOKS :"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserStats = QtWidgets.QMainWindow()
    ui = Ui_UserStats()
    ui.setupUi(UserStats)
    UserStats.show()
    sys.exit(app.exec_())
